// Code generated by `spike tui`. DO NOT EDIT — rebuild instead.
//
// This is the TUI equivalent of the HTML harness: it supplies the variant
// picker, the state axes, the footer, the geometry assertion and the frame
// dump, so a prototype author writes only variants.go.
//
// The harness bar is chrome. It is drawn OUTSIDE the design's own frame and is
// omitted from dumps, so a dumped frame is the design alone at exactly W×H.
package main

import (
	"flag"
	"fmt"
	"os"
	"regexp"
	"sort"
	"strings"

	tea "github.com/charmbracelet/bubbletea"
	"github.com/charmbracelet/lipgloss"
)

// State is what a variant renders against: every axis value, by key.
type State struct {
	Values map[string]string
	W, H   int // the design's own area, harness bar excluded
}

func (s State) Is(key, value string) bool { return s.Values[key] == value }
func (s State) Get(key string) string     { return s.Values[key] }

// Variant is one direction being compared. Render returns the design's frame:
// exactly H lines of exactly W visible columns. The harness checks both.
type Variant struct {
	Name    string
	Caption string
	Render  func(State) string
}

// Axis is a state dimension — which screen, which error, which connection state.
// Axes are orthogonal to variant on purpose: flipping direction must not reset
// which screen you are looking at, because comparing one screen across two
// directions is the entire job.
type Axis struct {
	Key    string
	Label  string
	Values []string
}

var ansiRe = regexp.MustCompile(`\x1b\[[0-9;]*m|\x1b\][^\x07\x1b]*(\x07|\x1b\\)`)

// Strip removes ANSI so width can be measured and frames dumped as plain text.
func Strip(s string) string { return ansiRe.ReplaceAllString(s, "") }

// VW is visible width in runes. Box-drawing characters are three bytes each in
// UTF-8, so byte length is always wrong for a character grid.
func VW(s string) int { return len([]rune(Strip(s))) }

// Pad extends s to w visible columns, or truncates it to w.
func Pad(s string, w int) string {
	n := VW(s)
	if n < w {
		return s + strings.Repeat(" ", w-n)
	}
	if n > w {
		r := []rune(Strip(s))
		return string(r[:w])
	}
	return s
}

type model struct {
	vi    int
	axes  map[string]int
	w, h int
}

func newModel() model {
	m := model{axes: map[string]int{}}
	return m
}

// size is the design's own area: the terminal minus the harness bar, floored so
// a zero or absurd WindowSizeMsg can never produce a negative slice bound. A
// terminal that reports 0x0 — a pty that has not been sized yet, a multiplexer
// pane mid-attach — is normal, not an error, and must still render.
func (m model) size() (int, int) {
	w, h := m.w, m.h-1
	if w < 1 {
		w = DumpWidth
	}
	if h < 1 {
		h = DumpHeight
	}
	return w, h
}

func (m model) state() State {
	v := map[string]string{}
	for _, a := range Axes {
		if len(a.Values) > 0 {
			v[a.Key] = a.Values[m.axes[a.Key]%len(a.Values)]
		}
	}
	w, h := m.size()
	return State{Values: v, W: w, H: h}
}

func (m model) Init() tea.Cmd { return nil }

func (m model) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	switch msg := msg.(type) {
	case tea.WindowSizeMsg:
		m.w, m.h = msg.Width, msg.Height
		return m, nil
	case tea.KeyMsg:
		switch msg.String() {
		case "ctrl+c", "Q":
			return m, tea.Quit
		case "]", "shift+right":
			if len(Variants) > 0 {
				m.vi = (m.vi + 1) % len(Variants)
			}
			return m, nil
		case "[", "shift+left":
			if len(Variants) > 0 {
				m.vi = (m.vi - 1 + len(Variants)) % len(Variants)
			}
			return m, nil
		}
		// F1..F9 cycle axis 1..9 — chosen so the design keeps every ordinary key.
		for i, a := range Axes {
			if i < 9 && msg.String() == fmt.Sprintf("f%d", i+1) {
				m.axes[a.Key] = (m.axes[a.Key] + 1) % max(1, len(a.Values))
				return m, nil
			}
		}
	}
	// Everything the harness did not claim belongs to the design.
	if h, ok := any(Variants[m.vi]).(interface{ Key(tea.Msg) }); ok {
		h.Key(msg)
	}
	return m, nil
}

func (m model) View() string {
	w, h := m.size()
	body := Variants[m.vi].Render(m.state())
	lines := strings.Split(strings.TrimRight(body, "\n"), "\n")
	for len(lines) < h {
		lines = append(lines, "")
	}
	lines = lines[:h]
	for i := range lines {
		lines[i] = Pad(lines[i], w)
	}
	return strings.Join(lines, "\n") + "\n" + m.bar()
}

// bar is harness chrome: what you are looking at, and how to change it. It never
// uses the design's own styling, so it reads as chrome rather than as part of
// the thing being judged.
func (m model) bar() string {
	c := lipgloss.NewStyle().Foreground(lipgloss.ANSIColor(0)).Background(lipgloss.ANSIColor(7))
	k := lipgloss.NewStyle().Foreground(lipgloss.ANSIColor(0)).Background(lipgloss.ANSIColor(7)).Bold(true)
	var b strings.Builder
	if len(Variants) > 1 {
		b.WriteString(k.Render(" [ ] "))
		b.WriteString(c.Render(fmt.Sprintf("%s (%d/%d) ", Variants[m.vi].Name, m.vi+1, len(Variants))))
	}
	for i, a := range Axes {
		if i >= 9 {
			break
		}
		b.WriteString(k.Render(fmt.Sprintf(" F%d ", i+1)))
		b.WriteString(c.Render(fmt.Sprintf("%s: %s ", a.Label, m.state().Get(a.Key))))
	}
	b.WriteString(k.Render(" ⇧Q "))
	b.WriteString(c.Render("quit "))
	w, _ := m.size()
	return c.Render(Pad(b.String(), w))
}

// ---- dump ----

func slug(s string) string {
	s = strings.ToLower(s)
	s = regexp.MustCompile(`[^a-z0-9]+`).ReplaceAllString(s, "-")
	return strings.Trim(s, "-")
}

// combos expands every axis into the full cross product, so no named state is
// silently missing from the dump.
func combos() []map[string]string {
	out := []map[string]string{{}}
	for _, a := range Axes {
		if len(a.Values) == 0 {
			continue
		}
		var next []map[string]string
		for _, base := range out {
			for _, v := range a.Values {
				c := map[string]string{}
				for k, vv := range base {
					c[k] = vv
				}
				c[a.Key] = v
				next = append(next, c)
			}
		}
		out = next
	}
	return out
}

func dump(dir string, w, h int) int {
	lipgloss.SetColorProfile(0) // Ascii — a dumped frame pins geometry, not colour
	bad, wrote := 0, 0
	for vi, v := range Variants {
		for _, c := range combos() {
			body := Strip(v.Render(State{Values: c, W: w, H: h}))
			lines := strings.Split(strings.TrimRight(body, "\n"), "\n")
			name := stateName(c)
			if len(Variants) > 1 {
				name = slug(v.Name) + "-" + name
			}
			if len(lines) != h {
				fmt.Printf("FAIL %-34s %d rows, want %d\n", name, len(lines), h)
				bad++
			}
			for i, l := range lines {
				if n := len([]rune(l)); n != w {
					fmt.Printf("FAIL %-34s row %d is %d cols, want %d\n", name, i, n, w)
					bad++
				}
			}
			if err := os.WriteFile(dir+"/"+name+".txt", []byte(body+"\n"), 0o644); err != nil {
				fmt.Println("write:", err)
				return 1
			}
			fmt.Printf("ok   %-34s %dx%d\n", name, w, h)
			wrote++
		}
		_ = vi
	}
	if bad > 0 {
		fmt.Printf("\n%d geometry violations\n", bad)
		return 1
	}
	fmt.Printf("\n%d frames, all %dx%d\n", wrote, w, h)
	return 0
}

func stateName(c map[string]string) string {
	if len(c) == 0 {
		return "frame"
	}
	keys := make([]string, 0, len(c))
	for k := range c {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	parts := make([]string, 0, len(keys))
	for _, k := range keys {
		parts = append(parts, slug(c[k]))
	}
	return strings.Join(parts, "-")
}

func max(a, b int) int {
	if a > b {
		return a
	}
	return b
}

func main() {
	d := flag.Bool("dump", false, "write every variant × state as a .txt frame and exit")
	dir := flag.String("dir", ".", "directory to write frames into")
	w := flag.Int("w", DumpWidth, "dump width in columns")
	h := flag.Int("h", DumpHeight, "dump height in rows")
	flag.Parse()

	if len(Variants) == 0 {
		fmt.Println("no variants declared — see variants.go")
		os.Exit(1)
	}
	if *d {
		os.Exit(dump(*dir, *w, *h))
	}
	if _, err := tea.NewProgram(newModel(), tea.WithAltScreen()).Run(); err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}
